import java.io.IOException;

import javax.servlet.Servlet;
import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

@WebServlet("/login")
public class Login extends HttpServlet{

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.setContentType("text/html");
        String html =       "<h1>Enter your Login Details</h1>" +
                            "<form action=\"Authenticate\" method=\"post\">"+
                            "User Name:<input type=\"text\" name=\"user\" required/>"+
                            "<br/>" +
                            "Password:<input type=\"password\" name=\"password\" required/>"+
                            "<br />"+
                            "<input type=\"submit\" value=\"Submit\" />";
        resp.getWriter().println(html);
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        // TODO Auto-generated method stub
        super.doPost(req, resp);
    }
    
    
}
